name: Build and Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main   # ajuste se sua branch principal for outra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        working-directory: WoodWork
        run: npm ci

      - name: Build (Vite)
        working-directory: WoodWork
        run: npm run build

      - name: Create .nojekyll file to avoid Jekyll processing
        run: |
          mkdir -p dist
          touch dist/.nojekyll
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3 # Or actions/upload-artifact@v4 if packaging manually
        with:
          path: ./_site # Or wherever your built site files are located
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
